### ISSUE TITLE
Error creating bean with name 'initDbService'

### ISSUE THREAD

**Issue by xuqisheng** [DanielMichalski/spring-web-rss-channels#1]
hello, when i run this project,i get bellow error.

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initDbService': Invocation of init method failed; nested exception is javax.validation.ValidationException: HV000028: Unexpected exception during isValid call.`

![63319cfe-e579-4bf7-8510-6d14381ac4ae](https://cloud.githubusercontent.com/assets/4362447/19795944/030aeb64-9d13-11e6-85ae-0f9b0f5ed05a.png)

**Comment by DanielMichalski** [comment]
Please update your project. I've already fixed it.

![app](https://cloud.githubusercontent.com/assets/5454114/19796136/6dd7ec34-9ce2-11e6-8bb8-19f4afe0edb5.png)
![log](https://cloud.githubusercontent.com/assets/5454114/19796135/6dd428ce-9ce2-11e6-91b7-9fb493d121bb.png)

**Comment by xuqisheng** [comment]
work!
